### PR TITLE
Tor

### PR DESCRIPTION
**Pull request by catatonicprime**
Creating TOR management module. This module provides the following functionality:

- Install/remove tor package
- Add/remove hidden services
- Add/remove port forwards for each hidden service

This means the tetra becomes effective at "NAT punching" & creates a unique opportunity to improve the anonymity of the manager/tester by providing a TOR backdoor into the connected network. 

Suggested use-cases are:
- Create management hidden service by forwarding 80 to 127.0.0.1:1471 and use TOR browser to manage .onion.
- Create SSH management hidden service by forwarding 22 to 127.0.0.1:22 and use torify + ssh to manage .onion.
- Create port forwarding pivots by forwarding ports to remote hosts and use torify/proxychains to perform pivoting attacks.

Known issues & areas I'd already like to see additional improvements.
- no input validation in the front-end
- input validation in the backend is rudimentary regex and possibly overly strict when present
- missing service:port in use check minor bug, will fix in the future
- Needs additional documentation
- I wrote it

### CODE REVIEW

**Comment by sebkinne** [comment]
@catatonicprime this looks great! Is there any reason the module.info only allows the TETRA? Looking over the code, it looks like you are also supporting installations to the SD card which is only relevant on the NANO.

I would also recommend using PSR-2 as a coding style for your PHP code :)

**Comment by catatonicprime** [comment]
Originally started working to bring it to the nano, but had some problems. I hope to correct this short coming into the future, just getting a mvp out the door.

PSR-2 don't know anything about it but I'll look into it.

**Comment by catatonicprime** [comment]
You guys should note PSR-2 on the contribution guidelines & provide some intelligence on how to achieve styling compliance. In my case installed php-codesniffer & ran it against the php.

So on the nano front I intend to keep developing to get the nano supported, the pkg is there, it's too big to fit on nano so sd is required, and LD path stuff gets all funky, etc. etc. Just needs some extra care and feeding before it's ready.

**Comment by catatonicprime** [comment]
Alright... looks like it can in fact install on the nano as well. It functions semi-decently on the tetra. Pretty brutal on the nano but I've been able to successfully load the page with the tor-browser / torify ssh root@blahblahblah.onion. So... that's kinda cool. Looks like the opkg for *just* tor fails so I tacked in tor-geoip & voila it starts working. I'm guessing some kind of dependency chain that's broken.

**Comment by catatonicprime** [comment]
I think that's everything you asked for++; module is passing php code sniffer for PSR2, static code analysis (sonarqube), and has been tested on a tetra & a nano. Changes fix items originally in the known issues list. I think its at least functional if not also usable now.

**Pull request merged**
