### PR TITLE
Status | Added defaulting "Auto Refresh" option for status module

### PR DESCRIPTION
**Pull request by trashbo4t**
I find the interface is much more useful when the panes auto refresh themselves.

### CODE REVIEW

**Comment by Foxtrot** [comment]
Thanks for making these improvments. As you're using `$interval`, it is required that you cancel it on scope destruction, otherwise the timer will continue in the background after the module has been exited.

You can fix this by appending the following code to the bottom of the AngularJS Controllers you define the intervals in.
```
$scope.$on('$destroy', function() {
	$interval.cancel($scope.yourIntervalVariable);
});```

Cheers,
Foxtrot

**Comment by trashbo4t** [comment]
> 
> 
> Thanks for making these improvments. As you're using `$interval`, it is required that you cancel it on scope destruction, otherwise the timer will continue in the background after the module has been exited.
> 
> You can fix this by appending the following code to the bottom of the AngularJS Controllers you define the intervals in.
> 
> ```
> $scope.$on('$destroy', function() {
> 	$interval.cancel($scope.yourIntervalVariable);
> });
> ```
> 
> Cheers,
> Foxtrot

Sorry for the late change, I have added the interval cancels. 
Nice catch as I had no idea this was required practice.

- T

**Comment by Foxtrot** [comment]
Thank you! :)

**Comment by trashbo4t** [comment]
> 
> 
> Thank you! :)

See you at DEF CON!

**Pull request merged**
