### PR TITLE
Using HTTPS for macvendor lookups instead of HTTP

### PR DESCRIPTION
**Pull request by trashbo4t**

### CODE REVIEW

**Comment by sebkinne** [comment]
Hi @trashbo4t,

I see this PR updates multiple modules, and that not all changes are related to the http -> https fix.

Would you mind amending the PR to keep it in line with the title?

**Comment by trashbo4t** [comment]
@sebkinne 

Woops, removed that SSLsplit change that was intended for a different branch

PTAL.

**Comment by sebkinne** [comment]
One more thing, sorry for overlooking it before - the Status module is missing its version bump

**Comment by trashbo4t** [comment]
@sebkinne Fixed

**Comment by sebkinne** [comment]
Thanks @trashbo4t! Merged.

**Pull request merged**
