### PR TITLE
PMKIDAttack - Add module for fw 2.7

### PR DESCRIPTION
**Pull request by xchwarze**
Add PMKIDAttack module from https://github.com/xchwarze/wifi-pineapple-pmkidattack

### CODE REVIEW

**Comment by foxtrot** [comment]
Sorry, pre-compiled binaries are not accepted.

**Comment by xchwarze** [comment]
The binarias are from adde88 repo https://github.com/adde88/openwrt-useful-tools/tree/packages-19.07_mkvi
If you wish I can make it download them with wget

**Comment by foxtrot** [comment]
Those tools should be available via opkg. Please use that instead.

**Comment by xchwarze** [comment]
mmmm it seems that hcxtools is not here
```
root@Pineapple:~# opkg --dest sd install hcxtools-custom hcxdumptool-custom
Unknown package 'hcxtools-custom'.
Unknown package 'hcxdumptool-custom'.
Collected errors:
 * opkg_install_cmd: Cannot install package hcxtools-custom.
 * opkg_install_cmd: Cannot install package hcxdumptool-custom.
root@Pineapple:~# opkg --dest sd install hcxtools hcxdumptool
Unknown package 'hcxtools'.
Installing hcxdumptool (6.0.1-1) to sd...
Downloading https://downloads.openwrt.org/releases/packages-19.07/mips_24kc/packages/hcxdumptool_6.0.1-1_mips_24kc.ipk
Configuring hcxdumptool.
Collected errors:
 * opkg_install_cmd: Cannot install package hcxtools.

```

**Comment by xchwarze** [comment]
@foxtrot Any ideas to fix this? 
The module really has a lot of work on it and I think it's a shame not to share it

**Comment by foxtrot** [comment]
@xchwarze I package hcxtools for the Mark 7, so tomorrow I'll backport it to the NANO and TETRAs feed for you.

**Comment by xchwarze** [comment]
thanks!

**Comment by foxtrot** [comment]
Hi,

Sorry for the delay. I've pushed hcxtools to the repository. You can get it with opkg update && opkg install hcxtools.

I'll review the module within the next few days.

**Comment by xchwarze** [comment]
Commit 0446600 seems to work ok with hcxpcapngtool 6.1

**Comment by xchwarze** [comment]
@foxtrot I tested commit 542cc6d all weekend without any error.

**Comment by xchwarze** [comment]
Hi @foxtrot! 
Is there any chance you can see this pull request and https://github.com/hak5/nano-tetra-modules/pull/96 ?

**Pull request closed without merging**
