### PR TITLE
SSLsplit log directory affirmation and generation 

### PR DESCRIPTION
**Pull request by trashbo4t**

### CODE REVIEW

**Comment by Hacksawfred3232** [comment]
I have a more cleaner but verbose version here: https://github.com/hak5/wifipineapple-modules/pull/19

**Comment by trashbo4t** [comment]
Commented.

**Comment by trashbo4t** [comment]
Please do not delete comments to help create a negative image about my comment 
image

**Comment by Hacksawfred3232** [comment]
I deleted that comment because you treated me with such disrespect that i decided to discredit you in my work.

**Comment by Hacksawfred3232** [comment]
I.E, this BS here: 

> (not pragmatically of course).
What you have implemented is the wrong way to check for directory existence in BASH.
your directory check is non-intuitive without further inspection, and the overall creation method is non standard for this repository.

**Comment by Hacksawfred3232** [comment]
In fact, for a more verbose script that works in the end and does not include broken bits of code that bugs out and never does anything, how about this PR for a change? #20

**Comment by sebkinne** [comment]
@trashbo4t @Hacksawfred3232 - 

I do not want to have non-constructive arguments in these repositories. Opinions should be heard and constructive criticism welcomed.

I am going to accept this PR instead of #20 because it creates a directory in the same style that @WhistleMaster uses throughout his projects, and I would like to maintain consistency.

If there are issues with log file creation, a simple `touch <path>/<log_name>` should be added after the mkdir.

**Comment by Hacksawfred3232** [comment]
@sebkinne You kidding me? You accepting this nitwit!? Seb, this guy insulted me because i made a simple function in a script. My script does exactly the same thing AND it makes sure it stays that way, this guys scripts is going to break again! PR #14 should have worked, except it did not! And this guys idea of constructive criticism is diabolical! I suggest you reconsider, my evidence is this: 
image
Do you agree with me that user interfaces should be clean and user-friendly? Do you think for a device such as the WiFi-pineapple that it should give more information about why something went wrong? If so, revert the PR and accept mine instead. Trust me, its better than using broken code as such as #14 or #18.

**Comment by sebkinne** [comment]
@Hacksawfred3232 -

Ignoring all of the comments before and just judging the code:

- There is nothing wrong with this `if` statement that I can see - it's perfectly valid SH / Bash
- I prefer a more verbose `if` statement than a one-liner, as it's clearer to anyone else reading the script to understand
- The way the `if` statement was written also better matches the coding style by WM, the module's author, which I would like to adhere to
- There is no need to echo something to a file if the file is created by a different process. If it is not, I would rather create it using `touch`.

**Comment by Hacksawfred3232** [comment]
Okay then, why did this not work?:
`	+MODULEDIR=/pineapple/modules/wps
+LOGDIR=$MODULEDIR/log
+ 
+# ensure log directory is created
+if [ ! -d $LOGDIR ]; then
+	mkdir $LOGDIR
+fi`

**Comment by Hacksawfred3232** [comment]
That's from PR #14. And that was supposed to get the job done.

**Pull request merged**
