### PR TITLE
PortalAuth v1.9

### PR DESCRIPTION
**Pull request by sud0nick**

### CODE REVIEW

**Comment by sud0nick** [comment]
Seb, I'm not sure why the merge conflicts are there.  Is it possible for you to just overwrite with the latest I've submitted?  It says the conflicts are too complex to resolve in the web editor but I'm not even sure what the conflicts are at the moment.

**Comment by sud0nick** [comment]
@Foxtrot is it possible to merge and overwrite the conflicts?

**Comment by Foxtrot** [comment]
@sud0nick I cannot solve the merge conflicts for you. You must resolve them yourself over the command line in this PR. Click on the "Use the command line" link and scroll to the bottom to see instructions on how to do that.

**Comment by Foxtrot** [comment]
@sud0nick Does this PR resolve #45 ?

**Pull request closed without merging**
