### PR TITLE
Update index.php

### PR DESCRIPTION
**Pull request by H4xl0r**
fixed destination to support https and http

### CODE REVIEW

**Comment by mjnohai** [comment]
@sebkinne please review and merge.

**Comment by sebkinne** [comment]
@foxtrot will take care of it. I no longer work for Hak5.

**Comment by Foxtrot** [comment]
Hi,

If possible, I would like these two changes (#55 and #54) to be in one pull request, instead of being seperate. Please also remember to bump the module version by .1, in the module.json file.

**Comment by H4xl0r** [comment]
where is the problem ? just get both pulls or have a view on the changes (not big no bog deal) 
sorry but i am not the real owner of this project and i dont want to get it 
they should take the pulls for a better version , but its up to them 
if you need a version with both fixes just load from my rep .... they are both inculded

**Comment by Foxtrot** [comment]
@H4xl0r I'm sorry if it came off like I wanted to disregard your PR - That isn't the case (It is still open). I simply asked if you could make the changes to the module with one pull request instead of two, and to increase the version number.

**Comment by H4xl0r** [comment]
no i wasn't offended all cool will see what i can do

**Pull request closed without merging**
